// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU5ogLngbisOxkt4EW0FY5gxm1ISvk0os',
    appId: '1:539547164918:web:7b4ef6021722cd45c20cd7',
    messagingSenderId: '539547164918',
    projectId: 'ar-proj-itu',
    authDomain: 'ar-proj-itu.firebaseapp.com',
    storageBucket: 'ar-proj-itu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZrA73QdRp0lnq2OmsjZB4BhhsIxp1S1k',
    appId: '1:539547164918:android:e57b89ac733a58a3c20cd7',
    messagingSenderId: '539547164918',
    projectId: 'ar-proj-itu',
    storageBucket: 'ar-proj-itu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1qBKaXFuaV_qnuPiULGUoPGj3K-fnE8',
    appId: '1:539547164918:ios:fd8e7a552b1d816bc20cd7',
    messagingSenderId: '539547164918',
    projectId: 'ar-proj-itu',
    storageBucket: 'ar-proj-itu.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz1qBKaXFuaV_qnuPiULGUoPGj3K-fnE8',
    appId: '1:539547164918:ios:fd8e7a552b1d816bc20cd7',
    messagingSenderId: '539547164918',
    projectId: 'ar-proj-itu',
    storageBucket: 'ar-proj-itu.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU5ogLngbisOxkt4EW0FY5gxm1ISvk0os',
    appId: '1:539547164918:web:b82874fc57deca74c20cd7',
    messagingSenderId: '539547164918',
    projectId: 'ar-proj-itu',
    authDomain: 'ar-proj-itu.firebaseapp.com',
    storageBucket: 'ar-proj-itu.firebasestorage.app',
  );
}
